import type { AnalyzeResponse } from "../types/meeting";

function getCurrentDateString(): string {
  const options: Intl.DateTimeFormatOptions = { 
    year: 'numeric', 
    month: 'short', 
    day: '2-digit', 
    hour: 'numeric', 
    minute: '2-digit' 
  };
  return new Date().toLocaleDateString('en-US', options);
}

export function generateExportFilename(filename: string, ext: string): string {
  const dateStr = new Date().toISOString().split("T")[0]; // YYYY-MM-DD
  
  // Clean up filename (remove extension, replace spaces with underscores)
  const baseName = filename
    ? filename.replace(/\.[^/.]+$/, "").replace(/\s+/g, "_")
    : "Report";

  return `MeetingIQ_${baseName}_${dateStr}.${ext}`;
}

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

const buildList = (items: string[], bullet: string = "-"): string => {
  if (!items || items.length === 0) return "None\n";
  return items.map(item => `${bullet} ${item}`).join("\n") + "\n";
};

export function generateMarkdown(result: AnalyzeResponse, includeTranscript: boolean): string {
  const { analysis, transcript } = result;
  const dateStr = getCurrentDateString();

  let md = `# MeetingIQ Report\n\n`;

  md += `## Executive Summary\n${analysis.executive_summary}\n\n`;
  if (analysis.detailed_summary) {
    md += `${analysis.detailed_summary}\n\n`;
  }

  md += `## Action Items\n${buildList(analysis.action_items)}\n`;
  md += `## Deadlines\n${buildList(analysis.deadlines)}\n`;
  md += `## Pending Decisions\n${buildList(analysis.pending_decisions)}\n`;
  md += `## Goals\n${buildList(analysis.goals)}\n`;
  md += `## Requirements\n${buildList(analysis.requirements)}\n`;
  md += `## Constraints\n${buildList(analysis.constraints)}\n`;
  md += `## Risk Assessment\n${buildList(analysis.risks)}\n`;

  if (includeTranscript && transcript) {
    md += `## Transcript\n${transcript}\n\n`;
  }

  md += `--------------------------------------------------\n`;
  md += `Generated by MeetingIQ\n`;
  md += `Generated on: ${dateStr}\n`;
  md += `--------------------------------------------------\n`;

  return md;
}

export function generatePlainText(result: AnalyzeResponse, includeTranscript: boolean): string {
  const { analysis, transcript } = result;
  const dateStr = getCurrentDateString();
  const sep = `==================================================\n`;
  const subSep = `--------------------------------------------------\n`;

  let txt = sep;
  txt += `MEETING REPORT\n`;
  txt += sep + `\n`;

  txt += `Executive Summary\n${subSep}`;
  txt += `${analysis.executive_summary}\n\n`;
  if (analysis.detailed_summary) {
    txt += `${analysis.detailed_summary}\n\n`;
  }

  txt += `Action Items\n${subSep}${buildList(analysis.action_items, "•")}\n`;
  txt += `Deadlines\n${subSep}${buildList(analysis.deadlines, "•")}\n`;
  txt += `Pending Decisions\n${subSep}${buildList(analysis.pending_decisions, "•")}\n`;
  txt += `Goals\n${subSep}${buildList(analysis.goals, "•")}\n`;
  txt += `Requirements\n${subSep}${buildList(analysis.requirements, "•")}\n`;
  txt += `Constraints\n${subSep}${buildList(analysis.constraints, "•")}\n`;
  txt += `Risk Assessment\n${subSep}${buildList(analysis.risks, "•")}\n`;

  if (includeTranscript && transcript) {
    txt += `Transcript\n${subSep}${transcript}\n\n`;
  }

  txt += subSep;
  txt += `Generated by MeetingIQ\n`;
  txt += `Generated on: ${dateStr}\n`;
  txt += subSep;

  return txt;
}
